[tool.poetry]
name = "sanruum"
version = "0.1.0"
description = ""
authors = ["Raimo Jostov <sanruumou@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pathspec = "^0.12.1"
colorama = "^0.4.6"
colorlog = "^6.9.0"
fuzzywuzzy = "^0.18.0"
python-levenshtein = "^0.26.1"
pyttsx3 = "^2.98"
SpeechRecognition = "^3.14.1"

[tool.poetry.scripts]
sanruum = "sanruum.main:main"


[tool.poetry.group.dev.dependencies]
mypy = "^1.14.1"
flake8 = "^7.1.1"
black = "^25.1.0"

[tool.mypy]
ignore_missing_imports = true  # Keep this to avoid issues with libraries that lack type hints
disallow_untyped_calls = true  # Ensure that all calls are typed
disallow_untyped_defs = true   # Ensure all functions are typed
check_untyped_defs = true      # Check even functions without type hints
show_error_codes = true        # Display the error codes for more precise troubleshooting
warn_unused_ignores = true     # Warn if you have unused `# type: ignore`
warn_return_any = true         # Warn about functions that return `Any`
warn_incompatible_signature = true  # Warn if the function signature is incompatible with the base class (useful for OOP)

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
