name: Python Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Cache Poetry dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-


      #      - name: Install dependencies
      #        shell: pwsh
      #        run: |
      #          python -m pip install --upgrade pip
      #          pip install poetry
      #          poetry install

      - name: Debug pytest rootdir
        shell: cmd
        run: |
          poetry pytest --version
          poetry pytest --rootdir=D:/a/sanruum/sanruum --collect-only

      - name: Lint with flake8
        shell: pwsh
        run: |
          poetry flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          poetry flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Clear pytest cache
        shell: cmd
        run: |
          poetry pytest --cache-clear

      - name: Test with pytest
        shell: cmd
        working-directory: D:/a/sanruum/sanruum  # 👈 Set correct working directory
        run: |
          poetry pytest --cache-clear
          poetry pytest --cov=sanruum --cov-report=term-missing
