name: Python Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Cache Poetry dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.local/share/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install Dependencies
        run: poetry install --no-interaction --no-root

      - name: Install FFmpeg (required for pydub)
        run: choco install ffmpeg -y

      - name: **Download NLTK stopwords**
        run: poetry run python -c "import nltk; nltk.download('stopwords')"

      - name: Debug pytest rootdir
        run: |
          poetry run pytest --version
          poetry run pytest --rootdir=D:/a/sanruum/sanruum --collect-only

      - name: Lint with flake8
        run: |
          poetry run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          poetry run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Clear pytest cache
        run: poetry run pytest --cache-clear

      - name: Run Tests
        working-directory: D:/a/sanruum/sanruum
        run: |
          poetry run pytest --cov=sanruum --cov-report=term-missing
